# Generated by Django 4.2 on 2024-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_seats',
            field=models.IntegerField(default=0),
        ),
    ]
