# Generated by Django 4.2 on 2024-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_movie_num_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='num_seats',
        ),
        migrations.AddField(
            model_name='session',
            name='num_seats',
            field=models.IntegerField(default=0),
        ),
    ]
